/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Palm Tree.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Palm Tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Environment_PalmTree_3.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/Palm Tree.glb')
