/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Ship.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ship_Large.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('/Ship.glb')
