/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Rocketship.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rocketship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat3} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat13} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat14} />
    </group>
  )
}

useGLTF.preload('/Rocketship.glb')
