/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Office.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d'

export function Office(props) {
  const {section} = props
  const { nodes, materials } = useGLTF('./models/Office.glb')


  return (
    <group {...props} dispose={null}>
      <group position={[22.743, 0, 313.535]} scale={50}>

        {/* Monitors */}
        <group position={[-0.294, 1.285, -6.337]} rotation={[-Math.PI / 2, 0, 0]} scale={30.19}>
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group112678593|Dupli|5'].geometry} material={materials['mat22.001']} />
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1219313228|Dupli|2'].geometry} material={materials['mat22.001']} />
          
          {/* left screen */}
          <group position={[0, 0, -0.005]}>
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23001'].geometry} material={materials['mat22.001']} />
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23001_1'].geometry} material={materials['mat23.001']} />
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group1691283673|Dupli|23001_2'].geometry} material={materials['mat21.001']} />
          </group>
          
          {/* right screen */}
          <group position={[0, 0, -0.005]}>
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22001'].geometry} material={materials['mat22.001']} />
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22001_1'].geometry} material={materials['mat23.001']} />
            <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group860618825|Dupli|22001_2'].geometry} material={materials['mat21.001']} />
          </group>


          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group929043094|Dupli|10'].geometry} material={materials['mat22.001']} />
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|001'].geometry} material={materials['mat22.001']} />
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group329542522|Dupli|001_1'].geometry} material={materials['mat23.001']} />
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1001'].geometry} material={materials['mat22.001']} />
          <mesh geometry={nodes['Dual_Monitors_on_sit-stand_arm|group576947092|Dupli|1001_1'].geometry} material={materials['mat23.001']} />

        </group>



        <group position={[-0.805, 0.862, -6.105]} rotation={[-Math.PI / 2, 0, 0]} scale={129.646}>
          <mesh geometry={nodes['Mug_With_Office_Tool|Mug_with_office_tools|Dupli|'].geometry} material={materials['Material.002']} scale={100} />
        </group>
        <group position={[0.255, 0.867, -6.492]} rotation={[-Math.PI / 2, 0, -2.857]} scale={3.1}>
          <mesh geometry={nodes['Notebook|Notebook_Cube041|Dupli|001'].geometry} material={materials['FFEB3B.001']} />
          <mesh geometry={nodes['Notebook|Notebook_Cube041|Dupli|001_1'].geometry} material={materials['795548.001']} />
          <mesh geometry={nodes['Notebook|Notebook_Cube041|Dupli|001_2'].geometry} material={materials['F44336.001']} />
        </group>
        <motion.group position={[-1.161, 0.867, -6.524]} rotation={[-Math.PI / 2, 0, 0]} scale={18.63} animate={{}}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Soda001|Soda|Dupli|001'].geometry} material={materials['White.001']} />
            <mesh geometry={nodes['Soda001|Soda|Dupli|001_1'].geometry} material={materials['Red.001']} />
          </group>
        </motion.group>
        <group position={[-1.101, 0.867, -6.167]} rotation={[-Math.PI / 2, 0, 2.753]} scale={1.243}>
          <mesh geometry={nodes['Calendar-8GqQAqxi3qk001'].geometry} material={materials['Calendar_Texture.001']} />
          <mesh geometry={nodes['Calendar-8GqQAqxi3qk001_1'].geometry} material={materials['Calendar_Aquamarine.001']} />
          <mesh geometry={nodes['Calendar-8GqQAqxi3qk001_2'].geometry} material={materials['Calendar_Ivory.001']} />
          <mesh geometry={nodes['Calendar-8GqQAqxi3qk001_3'].geometry} material={materials['FrontColor.001']} />
        </group>
        <group position={[-0.456, 0, -6.33]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[100, 100, 90.91]}>
          <mesh geometry={nodes.Desk001.geometry} material={materials['BlackCoatSteel.002']} />
          <mesh geometry={nodes.Desk001_1.geometry} material={materials['GrayPlastic.002']} />
          <mesh geometry={nodes.Desk001_2.geometry} material={materials['WhiteSteelScrew.002']} />
          <mesh geometry={nodes.Desk001_3.geometry} material={materials['BlackPlastic.002']} />
          <mesh geometry={nodes.Desk001_4.geometry} material={materials['BlackWood.002']} />
        </group>
       
        <group position={[0.338, 0.935, -6.188]} rotation={[0, 0.144, Math.PI]} scale={781.608}>
          <mesh geometry={nodes.Office_Phone002.geometry} material={materials['Light grey.001']} />
          <mesh geometry={nodes.Office_Phone002_1.geometry} material={materials['Grey Plastic.001']} />
          <mesh geometry={nodes.Office_Phone002_2.geometry} material={materials['Screen.001']} />
          <mesh geometry={nodes.Office_Phone002_3.geometry} material={materials['Dark Grey Plastic.001']} />
        </group>
      </group>
      <group position={[-23.533, 15.731, -61.313]} scale={30.46}>
        <mesh geometry={nodes.ExecutiveChair1.geometry} material={materials.LeatherExecutiveChair1} position={[1.106, 0, 0.524]} rotation={[-Math.PI / 2, 0, 0]} scale={156.384} />
      </group>
      
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh549538436.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh549538436_1.geometry} material={materials['mat8.001']} />
        <mesh geometry={nodes.mesh549538436_2.geometry} material={materials.mat24} />
      </group>
      <mesh geometry={nodes.group1867655503.geometry} material={materials.mat24} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group706968164.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1851977708.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh997898928.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh997898928_1.geometry} material={materials.mat16} />
      </group>
      <mesh geometry={nodes.group1874588551.geometry} material={materials['mat8.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group676697694.geometry} material={materials.mat21} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group194524521.geometry} material={materials.mat3} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group289168744.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group377627692.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2083473735.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1297143275.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1724716729.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group47713880.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group109271366.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group358629412.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1799644813.geometry} material={materials.mat10} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group563957055.geometry} material={materials.mat10} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1186992705.geometry} material={materials.mat9} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1144869753.geometry} material={materials.mat9} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group952295781.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1722992837.geometry} material={materials.mat15} />
        <mesh geometry={nodes.mesh1722992837_1.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1125399115.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1125399115_1.geometry} material={materials.mat15} />
      </group>
      <mesh geometry={nodes.group311705158.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2024160734.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group741402870.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group11151369.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1747962436.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1216547099.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1739615239.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group701415949.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1221721378.geometry} material={materials.mat16} />
        <mesh geometry={nodes.mesh1221721378_1.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1456472197.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1456472197_1.geometry} material={materials.mat16} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh139018155.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh139018155_1.geometry} material={materials.mat16} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh562682276.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh562682276_1.geometry} material={materials.mat16} />
      </group>
      <mesh geometry={nodes.group246477310.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh619239296.geometry} material={materials.mat16} />
        <mesh geometry={nodes.mesh619239296_1.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1783485154.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1783485154_1.geometry} material={materials.mat16} />
      </group>
      <mesh geometry={nodes.group1275655566.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1586564780.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2102640996.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1395154075.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh2029488445.geometry} material={materials.mat15} />
        <mesh geometry={nodes.mesh2029488445_1.geometry} material={materials['mat23.002']} />
      </group>
      <mesh geometry={nodes.group602384715.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1050079147.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1247630253.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1554204416.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group360414338.geometry} material={materials.mat10} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1332034770.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1714365479.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group968331571.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1338682067.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group310832378.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1817044955.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group252333627.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1013654719.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1664409649.geometry} material={materials.mat21} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group602345555.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group731708330.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1004135894.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group573210084.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group120898098.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group73605351.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1403669828.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group886964551.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1324414297.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group417210971.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1876175818.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1961792104.geometry} material={materials.mat10} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh148538432.geometry} material={materials.mat16} />
        <mesh geometry={nodes.mesh148538432_1.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh892610586.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh892610586_1.geometry} material={materials.mat16} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1002021246.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1002021246_1.geometry} material={materials.mat16} />
      </group>
      <mesh geometry={nodes.group438055053.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group740024917.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1179872976.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1800416953.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group335831164.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1033487155.geometry} material={materials.mat21} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh172225094.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh172225094_1.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1693732898.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1693732898_1.geometry} material={materials['mat17.001']} />
      </group>
      <mesh geometry={nodes.group893749766.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2032200821.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group676590036.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group761930540.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group897881202.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1526395978.geometry} material={materials.mat16} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group458008891.geometry} material={materials.mat21} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1977161757.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2094616060.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1620621923.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group376269877.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group79611238.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1634298705.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1017920957.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1411416077.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group395313063.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group774251851.geometry} material={materials['mat8.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1882511964.geometry} material={materials['mat8.001']} />
        <mesh geometry={nodes.mesh1882511964_1.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1882511964_2.geometry} material={materials['mat17.001']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh614062749.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh614062749_1.geometry} material={materials['mat8.001']} />
        <mesh geometry={nodes.mesh614062749_2.geometry} material={materials['mat23.002']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1403192981.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1403192981_1.geometry} material={materials['mat8.001']} />
        <mesh geometry={nodes.mesh1403192981_2.geometry} material={materials['mat17.001']} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1207655705.geometry} material={materials['mat23.002']} />
        <mesh geometry={nodes.mesh1207655705_1.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh1207655705_2.geometry} material={materials['mat8.001']} />
      </group>
      <mesh geometry={nodes.group2011638665.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group56262870.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1788593855.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group191747226.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1799134820.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1350575126.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1809112506.geometry} material={materials.mat12} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1051984110.geometry} material={materials.mat5} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group935673430.geometry} material={materials['mat8.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group833559944.geometry} material={materials.mat13} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1754797367.geometry} material={materials.mat13} />
        <mesh geometry={nodes.mesh1754797367_1.geometry} material={materials.mat2} />
      </group>
      <mesh geometry={nodes.group1548294784.geometry} material={materials.mat5} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group54598879.geometry} material={materials.mat3} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group912049542.geometry} material={materials['mat8.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2061932718.geometry} material={materials.mat12} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group229424706.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group367993755.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group675547103.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group239182004.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group508965083.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1601213803.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group287848248.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1562485891.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1381102080.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1578493595.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1403985160.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group2101908238.geometry} material={materials.mat15} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group47846800.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group95314420.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group713359564.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group854105041.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group332402059.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group704994766.geometry} material={materials.mat11} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1517310649.geometry} material={materials.mat11} />
        <mesh geometry={nodes.mesh1517310649_1.geometry} material={materials['mat23.002']} />
      </group>
      <mesh geometry={nodes.group1158745515.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1851189319.geometry} material={materials['mat22.003']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group961377794.geometry} material={materials.mat21} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group667732097.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1280736543.geometry} material={materials['mat17.001']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh381560967.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh381560967_1.geometry} material={materials.mat15} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1841586256.geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes.mesh1841586256_1.geometry} material={materials.mat15} />
      </group>
      <group position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475}>
        <mesh geometry={nodes.mesh1264231965.geometry} material={materials.mat15} />
        <mesh geometry={nodes.mesh1264231965_1.geometry} material={materials['mat17.001']} />
      </group>
      <mesh geometry={nodes.group587275507.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.group1644871367.geometry} material={materials['mat23.002']} position={[-27.212, 19.094, -9.505]} rotation={[0, -1.555, 0]} scale={17.475} />
      <mesh geometry={nodes.Keyboard1.geometry} material={materials['lambert3SG.001']} position={[11.986, 43.775, -16.028]} rotation={[Math.PI, -0.005, Math.PI]} scale={0.065} />
    </group>
  )
}

useGLTF.preload('./models/Office.glb')
