/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Can Character.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CanCharacter(props) {
  const { nodes, materials } = useGLTF('./models/CanCharacter.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh name="Body_9" geometry={nodes.Body_9.geometry} material={materials._082_GoodTomato} morphTargetDictionary={nodes.Body_9.morphTargetDictionary} morphTargetInfluences={nodes.Body_9.morphTargetInfluences} scale={100} />
    </group>
  )
}

useGLTF.preload('./models/CanCharacter.glb')
