/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Mimic.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mimic.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.Mimic_1.geometry} material={materials.Atlas_Diffuse} />
        <mesh geometry={nodes.Mimic_2.geometry} material={materials.Atlas_Unlit} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mimic.glb')
