/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Tree stump.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Tree stump.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree_stump.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/Tree stump.glb')
